package com.rihla.thanaweya;

import android.app.*;
import android.os.*;
import android.webkit.*;
import android.view.*;
import android.widget.*;
import android.content.*;

public class MainActivity extends Activity{
 WebView web;
 private static final String THEME="javascript:(function(){try{if(window.__rt)return;window.__rt=1;var s=document.createElement('style');s.textContent='.rihla-light body,.rihla-light .app{background:#eef7ff!important;color:#16324f!important}.rihla-light .card,.rihla-light .subject,.rihla-light .stat,.rihla-light .skill-box{background:linear-gradient(145deg,#fff,#e5f0fa)!important;color:#16324f!important}.rihla-light .nav{background:#fafdff!important}.rihla-light .input,.rihla-light .answer{background:#fff!important;color:#16324f!important}.rihla-light .auth-gate{background:radial-gradient(circle at 50% 0%,#dff8ff,transparent 38%),linear-gradient(145deg,#f7fcff,#dbeaf7)!important}.rihla-light .auth-box,.rihla-light .auth-box-v2{background:linear-gradient(145deg,#ffffff,#e8f3fb)!important;color:#16324f!important}.rihla-light .auth-box-v2 *{color:#16324f}.rihla-light .auth-box-v2 input{background:#fff!important;color:#16324f!important;border-color:#b8d7eb!important}.rihla-light .auth-note{background:#e8f5fc!important;color:#42617b!important}';document.head.appendChild(s);var b=document.createElement('button');b.id='rihlaThemeToggle';b.textContent='☀️ فاتح';b.style.cssText='position:fixed;top:14px;left:14px;z-index:9998;border:1px solid rgba(255,255,255,.25);border-radius:15px;padding:8px 11px;background:linear-gradient(145deg,#17466d,#0a223b);color:#fff;font-size:11px;font-weight:800;box-shadow:inset 2px 2px 4px rgba(255,255,255,.12),inset -3px -4px 7px rgba(0,0,0,.3),0 8px 18px rgba(0,0,0,.25)';document.body.appendChild(b);function m(l){document.documentElement.classList.toggle('rihla-light',l);b.textContent=l?'🌙 داكن':'☀️ فاتح';b.style.background=l?'linear-gradient(145deg,#fff,#dbeaf7)':'linear-gradient(145deg,#17466d,#0a223b)';b.style.color=l?'#16324f':'#fff';localStorage.setItem('rihlaTheme',l?'light':'dark')}m(localStorage.getItem('rihlaTheme')==='light');b.onclick=function(){m(!document.documentElement.classList.contains('rihla-light'))};function cleanLegacyColors(){try{document.querySelectorAll('.card').forEach(function(e){if((e.innerText||'').indexOf('لون التطبيق')!==-1)e.style.display='none'});document.querySelectorAll('div,section').forEach(function(e){var t=(e.innerText||'').trim();if(t==='لون التطبيق 🎨'||t==='لون التطبيق')e.style.display='none'})}catch(e){}}cleanLegacyColors();new MutationObserver(cleanLegacyColors).observe(document.body,{childList:true,subtree:true})}catch(e){}})();";
 private static final String AIUX="javascript:(function(){try{if(document.getElementById('rihlaAIUX'))return;var s=document.createElement('script');s.id='rihlaAIUX';s.src='file:///android_asset/www/aiux.js';document.head.appendChild(s)}catch(e){console.log('aiux',e)}})();";
 private static final String SOUND="javascript:(function(){if(window.__snd)return;window.__snd=1;let c=null,last=null;function u(){try{if(!c){let A=window.AudioContext||window.webkitAudioContext;if(A)c=new A()}if(c&&c.state==='suspended')c.resume()}catch(e){}}function d(){try{u();if(c){let t=c.currentTime+.03;[659,784,988,1319].forEach((f,i)=>{let o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.0001,t+i*.22);g.gain.exponentialRampToValueAtTime(.16,t+i*.22+.02);g.gain.exponentialRampToValueAtTime(.0001,t+i*.22+.2);o.connect(g);g.connect(c.destination);o.start(t+i*.22);o.stop(t+i*.22+.23)})}if(navigator.vibrate)navigator.vibrate([80,60,120])}catch(e){}}document.addEventListener('pointerdown',u,{passive:true});setInterval(function(){let e=document.querySelector('.timer-in strong'),m=e&&String(e.textContent).match(/^([0-9]+):([0-9]{2})$/),n=m?Number(m[1])*60+Number(m[2]):null;if(last!==null&&last>0&&n===0)d();last=n},200)})();";
 private static final String NAV="javascript:(function(){try{if(window.__rihlaNavV2)return;window.__rihlaNavV2=1;var st=window.__rihlaScreenStack=['home'];var original=window.showScreen;function current(){var a=document.querySelector('.screen.active');return a&&a.id?a.id:'home'}function sync(){var id=current();var x=document.getElementById('rihlaPageClose');var ex=document.getElementById('rihlaExitApp');if(x)x.style.display=id==='home'?'none':'flex';if(ex)ex.style.display=id==='home'?'flex':'none'}window.showScreen=function(id){try{if(typeof original==='function')original(id);else document.querySelectorAll('.screen').forEach(function(e){e.classList.toggle('active',e.id===id)});if(id&&id!=='home'&&st[st.length-1]!==id)st.push(id);else if(id==='home'&&st.length>1)st.length=1;sync()}catch(e){}};window.rihlaBack=function(){var id=current();if(document.querySelector('.modal.show')){document.querySelectorAll('.modal.show').forEach(function(m){m.classList.remove('show')});sync();return 'modal'}if(id!=='home'){if(st.length>1)st.pop();var p=st[st.length-1]||'home';if(typeof original==='function')original(p);else document.querySelectorAll('.screen').forEach(function(e){e.classList.toggle('active',e.id===p)});sync();return 'page'}return 'exit'};var style=document.createElement('style');style.id='rihla-nav-v2-css';style.textContent='#rihlaPageClose,#rihlaExitApp{position:fixed;left:14px;z-index:10001;display:flex;align-items:center;justify-content:center;border:0;border-radius:17px;font-weight:900;box-shadow:inset 2px 2px 5px rgba(255,255,255,.2),inset -4px -5px 9px rgba(0,0,0,.3),0 10px 22px rgba(0,0,0,.28)}#rihlaPageClose{top:14px;width:42px;height:42px;background:linear-gradient(145deg,#ff7185,#c92f4e);color:#fff;font-size:25px}#rihlaExitApp{bottom:82px;padding:10px 15px;background:linear-gradient(145deg,#ff7185,#8e203d);color:#fff;font-size:13px}#rihlaPageClose:active,#rihlaExitApp:active{transform:translateY(2px);box-shadow:inset -2px -2px 5px rgba(255,255,255,.1),inset 3px 4px 8px rgba(0,0,0,.35)}.rihla-light #rihlaPageClose{background:linear-gradient(145deg,#ff7b8c,#dc3e58)}';document.head.appendChild(style);var x=document.createElement('button');x.id='rihlaPageClose';x.textContent='×';x.title='إغلاق الصفحة';x.onclick=function(){window.rihlaBack()};document.body.appendChild(x);var ex=document.createElement('button');ex.id='rihlaExitApp';ex.textContent='خروج من التطبيق';ex.onclick=function(){if(window.Android&&Android.exitApp)Android.exitApp()};document.body.appendChild(ex);sync();new MutationObserver(sync).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']})}catch(e){}})();";
 private static final String BACK="javascript:(function(){try{var r=window.rihlaBack?window.rihlaBack():'exit';if(window.Android&&Android.backResult)Android.backResult(r)}catch(e){if(window.Android&&Android.backResult)Android.backResult('exit')}})();";
 @Override public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);web.setLayoutParams(new ViewGroup.LayoutParams(-1,-1));WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setMediaPlaybackRequiresUserGesture(false);web.addJavascriptInterface(new AppBridge(this),'Android');web.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){super.onPageFinished(v,u);v.evaluateJavascript("javascript:(function(){try{if(!document.getElementById('rihlaDarkModernTheme')){var l=document.createElement('link');l.id='rihlaDarkModernTheme';l.rel='stylesheet';l.href='file:///android_asset/www/dark-modern.css';document.head.appendChild(l)}if(!document.getElementById('rihla3DModernTheme')){var d=document.createElement('link');d.id='rihla3DModernTheme';d.rel='stylesheet';d.href='file:///android_asset/www/3d-modern.css';document.head.appendChild(d)}}catch(e){}})();",null);v.evaluateJavascript(THEME,null);v.evaluateJavascript(AIUX,null);v.evaluateJavascript(SOUND,null);v.evaluateJavascript(NAV,null);}});setContentView(web);web.loadUrl("file:///android_asset/www/index.html");}
 @Override public void onBackPressed(){web.evaluateJavascript(BACK,null);}
 public static class AppBridge{
  private final Activity a;
  AppBridge(Activity a){this.a=a;}
  @JavascriptInterface public void backResult(String r){if("exit".equals(r))a.finishAndRemoveTask();}
  @JavascriptInterface public void exitApp(){a.runOnUiThread(new Runnable(){public void run(){a.finishAndRemoveTask();}});}
 }
}
