package com.rihla.thanaweya;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.util.*;
public class NativeMainActivity extends Activity{
 int NAVY=Color.rgb(7,29,58),BLUE=Color.rgb(36,107,255),BG=Color.rgb(244,247,251),TEXT=Color.rgb(18,35,63),MUTED=Color.rgb(105,120,143),GREEN=Color.rgb(32,185,131),RED=Color.rgb(239,82,97); LinearLayout root,content; SharedPreferences p; int page=0,score=0,index=0;
 String[][] q={{"ما هو العنصر الذي رمزه O؟","الذهب","الأكسجين","الحديد","الهيدروجين"},{"كم عدد أيام الأسبوع؟","5","6","7","8"},{"ما عاصمة مصر؟","القاهرة","الإسكندرية","الأقصر","أسوان"}};
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("thanwia",0);getWindow().setStatusBarColor(NAVY);home();}
 int d(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} GradientDrawable g(int c,int r){GradientDrawable x=new GradientDrawable();x.setColor(c);x.setCornerRadius(d(r));return x;}
 TextView t(String s,float z,int c){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);x.setPadding(d(12),d(10),d(12),d(10));return x;}
 Button b(String s,int fg,int bg){Button x=new Button(this);x.setText(s);x.setTextColor(fg);x.setTextSize(14);x.setAllCaps(false);x.setBackground(g(bg,16));return x;}
 LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(d(14),d(12),d(14),d(12));x.setBackground(g(Color.WHITE,20));LinearLayout.LayoutParams z=new LinearLayout.LayoutParams(-1,-2);z.setMargins(0,0,0,d(12));x.setLayoutParams(z);return x;}
 void base(String s){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);Button back=b("‹",Color.WHITE,NAVY);back.setOnClickListener(v->goBack());top.addView(back,new LinearLayout.LayoutParams(d(52),d(62)));TextView h=t(s,21,Color.WHITE);h.setGravity(Gravity.CENTER);top.addView(h,new LinearLayout.LayoutParams(0,d(62),1));Button ex=b("×",Color.WHITE,NAVY);ex.setOnClickListener(v->finishAndRemoveTask());top.addView(ex,new LinearLayout.LayoutParams(d(52),d(62)));root.addView(top);ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(d(16),d(16),d(16),d(20));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void home(){page=0;base("رحلة الثانوية");content.addView(t("أهلاً بك في رحلة الثانوية 🎓",27,TEXT));content.addView(t("تعلّم، اختبر نفسك، وتابع تقدمك خطوة بخطوة.",14,MUTED));LinearLayout c=card();c.setBackground(g(BLUE,20));c.addView(t("جاهز تكمل؟",23,Color.WHITE));c.addView(t("ابدأ اختباراً قصيراً واحصل على نتيجة فورية.",13,Color.WHITE));Button z=b("ابدأ اختبار الآن",BLUE,Color.WHITE);z.setOnClickListener(v->quiz());c.addView(z);content.addView(c);quick("📝 الاختبارات","اختبر مستواك",v->exams());quick("👥 تحدي الأصدقاء","شارك كود التحدي",v->friends());quick("📊 تقدمي","درجاتك ومراجعتك",v->progress());quick("👤 حسابي","بياناتك وإعداداتك",v->profile());nav();}
 void quick(String a,String s,View.OnClickListener l){LinearLayout c=card();c.addView(t(a,17,TEXT));c.addView(t(s,12,MUTED));Button z=b("فتح",Color.WHITE,BLUE);z.setOnClickListener(l);c.addView(z);content.addView(c);}
 void exams(){page=1;base("الاختبارات");content.addView(t("اختر المادة",22,TEXT));String[] a={"📘 اللغة العربية","🇬🇧 اللغة الإنجليزية","🧪 الكيمياء","⚡ الفيزياء","🧬 الأحياء"};for(String s:a){LinearLayout c=card();c.addView(t(s,17,TEXT));c.addView(t("اختبار قصير • اختيار من متعدد",12,MUTED));Button z=b("ابدأ",Color.WHITE,BLUE);z.setOnClickListener(v->quiz());c.addView(z);content.addView(c);}nav();}
 void quiz(){page=2;score=0;index=0;question();} void question(){base("اختبار قصير  •  "+(index+1)+" / "+q.length);String[] x=q[index];content.addView(t(x[0],21,TEXT));for(int i=1;i<5;i++){final int k=i;Button z=b(x[i],TEXT,Color.WHITE);z.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);z.setOnClickListener(v->{boolean ok=(index==0&&k==2)||(index==1&&k==3)||(index==2&&k==1);if(ok)score++;new AlertDialog.Builder(this).setTitle(ok?"إجابة صحيحة 🎉":"إجابة غير صحيحة").setMessage(ok?"ممتاز! استمر بنفس التركيز.":"راجع الشرح وحاول مرة أخرى 💪").setPositiveButton(index+1<q.length?"التالي":"النتيجة",(a,w)->{index++;if(index<q.length)question();else result();}).show();});content.addView(z,new LinearLayout.LayoutParams(-1,d(58)));}}
 void result(){base("نتيجة الاختبار");LinearLayout c=card();c.setGravity(Gravity.CENTER);c.addView(t(score+" / "+q.length,45,BLUE));c.addView(t(score>=2?"ممتاز! أنت على الطريق الصحيح 👏":"راجع أخطاءك وحاول مرة أخرى 💪",17,TEXT));Button r=b("إعادة الاختبار",Color.WHITE,BLUE);r.setOnClickListener(v->quiz());c.addView(r);Button p2=b("مراجعة تقدمي",BLUE,Color.WHITE);p2.setOnClickListener(v->progress());c.addView(p2);content.addView(c);}
 void friends(){page=3;base("تحدي الأصدقاء");content.addView(t("⚔️ ابدأ تحدياً مع أصدقائك",23,TEXT));content.addView(t("أنشئ كوداً وشاركه مع أصدقائك أو أدخل كوداً وصلك.",13,MUTED));Button c=b("إنشاء تحدي جديد",Color.WHITE,BLUE);c.setOnClickListener(v->{String code="TH"+(100000+new Random().nextInt(900000));new AlertDialog.Builder(this).setTitle("تم إنشاء التحدي 🎯").setMessage("كود التحدي:\n\n"+code).setPositiveButton("ابدأ",(a,w)->quiz()).show();});content.addView(c);EditText e=new EditText(this);e.setHint("كود التحدي");content.addView(e);Button j=b("دخول التحدي",Color.WHITE,GREEN);j.setOnClickListener(v->{if(e.getText().toString().trim().length()<4)toast("اكتب كوداً صحيحاً");else quiz();});content.addView(j);nav();}
 void progress(){page=4;base("تقدمي");content.addView(t("📊 تقدمك الدراسي",23,TEXT));content.addView(t("آخر نتيجة: "+score+" / "+q.length,18,TEXT));content.addView(t("💡 عند الخطأ: راجع الدرس ثم أعد الاختبار. عند الإجابة الصحيحة: أحسنت، استمر!",14,MUTED));nav();}
 void profile(){page=5;base("الملف الشخصي");content.addView(t("👤 الملف الشخصي",23,TEXT));EditText e=new EditText(this);e.setHint("اسم الطالب");e.setText(p.getString("name",""));content.addView(e);Button s=b("حفظ الاسم",Color.WHITE,BLUE);s.setOnClickListener(v->{p.edit().putString("name",e.getText().toString().trim()).apply();toast("تم حفظ الاسم ✅");});content.addView(s);Button st=b("الإعدادات",TEXT,Color.WHITE);st.setOnClickListener(v->settings());content.addView(st);Button lo=b("تسجيل الخروج",Color.WHITE,RED);lo.setOnClickListener(v->{p.edit().clear().apply();home();});content.addView(lo);nav();}
 void settings(){base("الإعدادات");content.addView(t("الإعدادات",23,TEXT));Button x=b("🔐 تغيير كلمة السر",TEXT,Color.WHITE);x.setOnClickListener(v->toast("تغيير كلمة السر متاح عند تفعيل الحساب السحابي."));content.addView(x);Button a=b("ℹ️ عن التطبيق",TEXT,Color.WHITE);a.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("رحلة الثانوية").setMessage("تطبيق Android Native بدون WebView أو HTML لواجهة التطبيق.").setPositiveButton("حسناً",null).show());content.addView(a);}
 void nav(){LinearLayout n=new LinearLayout(this);n.setBackgroundColor(Color.WHITE);String[] a={"الرئيسية","الاختبارات","تحدي","تقدمي","حسابي"};for(String s:a){Button x=b(s,MUTED,Color.WHITE);x.setTextSize(11);if(s.equals("الرئيسية"))x.setOnClickListener(v->home());else if(s.equals("الاختبارات"))x.setOnClickListener(v->exams());else if(s.equals("تحدي"))x.setOnClickListener(v->friends());else if(s.equals("تقدمي"))x.setOnClickListener(v->progress());else x.setOnClickListener(v->profile());n.addView(x,new LinearLayout.LayoutParams(0,d(68),1));}root.addView(n);}
 void goBack(){if(page==0)finishAndRemoveTask();else home();}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
